services:
  postgres:
    container_name: database
    image: postgis/postgis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PGUSER=${PGUSER}
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - local
  liquibase:
    container_name: liquibase_update
    image: liquibase/liquibase
    volumes:
      - ./liquibase:/liquibase/changelog
    command:
      - --url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - --changeLogFile=changelog.xml
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - --log-level=1
      - update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local
#networks:
#  local:
#    driver: bridge