# coding: utf-8

"""
    Mobility Data Catalog API

    API as required in the _Proposed Version 1_ from the _Product Requirement Document for the Mobility Database_

    The version of the OpenAPI document: 0.1.0
    Contact: it@mobilitydata.org
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from feeds.apis.datasets_api import router as DatasetsApiRouter
from feeds.apis.feeds_api import router as FeedsApiRouter
from feeds.apis.metadata_api import router as MetadataApiRouter

app = FastAPI(
    title="Mobility Data Catalog API",
    description="API as required in the _Proposed Version 1_ from the _Product Requirement Document for the Mobility Database_",
    version="0.1.0",
)

app.include_router(DatasetsApiRouter)
app.include_router(FeedsApiRouter)
app.include_router(MetadataApiRouter)
