# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class BoundingBox(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    BoundingBox - a model defined in OpenAPI

        minimum_latitude: The minimum_latitude of this BoundingBox [Optional].
        maximum_latitude: The maximum_latitude of this BoundingBox [Optional].
        minimum_longitude: The minimum_longitude of this BoundingBox [Optional].
        maximum_longitude: The maximum_longitude of this BoundingBox [Optional].
    """

    minimum_latitude: Optional[float] = Field(alias="minimum_latitude", default=None)
    maximum_latitude: Optional[float] = Field(alias="maximum_latitude", default=None)
    minimum_longitude: Optional[float] = Field(alias="minimum_longitude", default=None)
    maximum_longitude: Optional[float] = Field(alias="maximum_longitude", default=None)

BoundingBox.update_forward_refs()
