@startuml
    hide stereotype
    hide circle
    hide empty members

    skinparam defaultFontName Heiti TC
    skinparam HeaderFontColor #96A1FF
    skinparam classFontColor automatic
    skinparam class {
        HeaderBackgroundColor<<enum>> MediumSlateBlue
        HeaderBackgroundColor<<entity>> #dedeff
        roundCorner 25
    }

    enum "=This is an enum" <<enum>> {
    active
    inactive
    development
    deprecated
    }

    entity "=This is an entity" <<entity>> {
    <color:MediumSlateBlue><&key></color> primary key
    <color:MediumSlateBlue><&key></color><&key> primary + foreign key
    <&key> foreign key
    }
@enduml