name: 'Notify Slack'
description: 'Send a notification to a Slack channel with an alert message based on priority level'
inputs:
  OP_SERVICE_ACCOUNT_TOKEN:
    description: 'The service account token for 1Password'
    required: true
    type: string
  PRIORITY:
    description: 'Priority level of the alert (medium/high/test)'
    required: true
    type: string
  STEP:
    description: 'The step in which the issue occurred (optional)'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: Load secrets from 1Password
      id: onepw_secrets
      uses: 1password/load-secrets-action@v2.0.0
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}
        CREDENTIALS: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/ifkeehu5gzi7wy5ub5qvwkaire/credential"
        SLACK_WEBHOOK_URL: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/Slack webhook URLs/internal-github-action-alerts/internal-github-action-alerts"

    - name: Set Alert Message
      id: alert_message
      shell: bash
      run: |
        case "${{ inputs.PRIORITY }}" in
          high)
            if [[ -n "${{ inputs.STEP }}" ]]; then
              message="🚨 High Priority Alert: [${{ github.workflow }}] failed at step \"${{ inputs.STEP }}\". Immediate attention is required to avoid production impact."
            else
              message="🚨 High Priority Alert: [${{ github.workflow }}] failed. Immediate attention is required to avoid production impact."
            fi
            ;;
          test)
            if [[ -n "${{ inputs.STEP }}" ]]; then
              message="🧪 Test Alert: [${{ github.workflow }}] reached step \"${{ inputs.STEP }}\". This is a test notification only."
            else
              message="🧪 Test Alert: [${{ github.workflow }}]. This is a test notification only."
            fi
            ;;
          *)
            if [[ -n "${{ inputs.STEP }}" ]]; then
              message="🚧 Medium Priority Alert: [${{ github.workflow }}] encountered an issue at step \"${{ inputs.STEP }}\". This may affect ongoing integration processes."
            else
              message="🚧 Medium Priority Alert: [${{ github.workflow }}] encountered an issue. This may affect ongoing integration processes."
            fi
            ;;
        esac

        # Construct the JSON payload and save it to a file
        jq -n --arg message "$message" --arg run_url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" '{
          "channel": "C074SPVCH6H",
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": $message,
                "emoji": true
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "See <\($run_url)|GitHub Action Run Details>"
              }
            }
          ]
        }' > slack_payload.json

    - name: Post notification in Slack channel
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload-file-path: ./slack_payload.json
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
