
name: 'Extract hash and version'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Retrieve and Store Commit Hash
      shell: bash
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "$COMMIT_HASH" > api/src/commit_hash

    - name: Write commit hash to file
      shell: bash
      run: ls -l api/src

    - name: Extract Version and Write to File on Release
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${{ github.ref }} 
          VERSION=${VERSION#refs/tags/}
          echo "$VERSION" > api/src/version
        else
          echo "N/A" > api/src/version
        fi