
name: 'Extract hash and version'
runs:
  using: "composite"
  steps:
    - name: Retrieve and Store Commit Hash
      shell: bash
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "$COMMIT_HASH" > api/src/commit_hash

    - name: Write commit hash to file
      shell: bash
      run: ls -l api/src

    - name: Extract Version and Write to File on Release
      shell: bash
      run: |
        VERSION=`git tag --sort=-creatordate | egrep  '^v\d+\.\d+\.\d+' | head -1`
        # Get all the tags. Then accept only tags with vX.X.X pattern. sort -V is great! It sorts with versions, so
        # v10.1.1 will come after v2.1.1. The last one after that should be the latest version
        if [ ! -z "$VERSION" ]; then
          VERSION="N/A"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "$VERSION" > api/src/version
