@startuml
    hide stereotype
    hide circle
    hide empty members

    skinparam defaultFontName Heiti TC
    skinparam HeaderFontColor #96A1FF
    skinparam classFontColor automatic

    skinparam class {
        HeaderBackgroundColor<<enum>> MediumSlateBlue
        HeaderBackgroundColor<<entity>> #dedeff
        roundCorner 25
    }

    enum =DataType <<enum>> {
    gtfs
    gtfs_rt
    }

    enum =Status <<enum>> {
    active
    inactive
    development
    deprecated
    }

    entity =Feed <<entity>> {
    <color:MediumSlateBlue><&key></color> id : varchar
      data_type : DataType
      provider : varchar
      feed_name : varchar
      note : varchar
      producer_url : varchar
      authentication_type : boolean
      authentication_info_url : varchar
      api_key_parameter_name : varchar
      license_url : varchar
      stable_id : varchar
      status: Status
      }

    entity =FeedHistory <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> id : varchar
    <color:MediumSlateBlue><&key></color> historical_record_time: Date
      data_type : DataType
      provider : varchar
      feed_name : varchar
      note : varchar
      producer_url : varchar
      authentication_type : boolean
      authentication_info_url : varchar
      api_key_parameter_name : varchar
      license_url : varchar
      stable_id : varchar
      status: Status
      }


    entity =GTFSRealtimeFeed <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> id : varchar
    }

    entity =EntityType <<entity>> {
    <color:MediumSlateBlue><&key></color> name : varchar
    }

    entity =EntityTypeFeed <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> entity_name : varchar
    <color:MediumSlateBlue><&key></color><&key> feed_id : varchar
      }

    entity =GTFSFeed <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> id : varchar
      }

    entity =FeedReference <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> gtfs_rt_feed_id : varchar
    <color:MediumSlateBlue><&key></color><&key> gtfs_feed_id : varchar
      }

    entity =Location <<entity>> {
    <color:MediumSlateBlue><&key></color> id : varchar
      country_code : varchar
      subdivision_name : varchar
      municipality : varchar
      }

    entity =LocationFeed <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> location_id : varchar
    <color:MediumSlateBlue><&key></color><&key> feed_id : varchar
      }

    entity =ExternalID <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> feed_id : varchar
    <color:MediumSlateBlue><&key></color> associated_id : varchar
      source : varchar
      }

    entity =GTFSDataset <<entity>> {
    <color:MediumSlateBlue><&key></color> id : varchar
    <&key> feed_id : varchar
      latest : boolean
      bounding_box : Geometry
      hosted_url : varchar
      note : varchar
      hash : varchar
      download_date : datetime
      creation_date : datetime
      last_update_date : datetime
      stable_id : varchar
      }

    entity =LocationGTFSDataset <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> location_id : varchar
    <color:MediumSlateBlue><&key></color><&key> dataset_id : varchar
      }

    entity =Component <<entity>> {
    <color:MediumSlateBlue><&key></color> name : varchar
      }

    entity =ComponentGTFSDataset <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> component : varchar
    <color:MediumSlateBlue><&key></color><&key> dataset_id : varchar
      }

      entity =RedirectingID <<entity>> {
    <color:MediumSlateBlue><&key></color><&key> source_id : varchar
    <color:MediumSlateBlue><&key></color><&key> target_id : varchar
      }

     "=Feed" ||-left-o{ "=FeedHistory"
     "=Feed" ||--o| "=GTFSRealtimeFeed"
     "=Feed" ||-right-o| "=GTFSFeed"
     "=FeedHistory" }--o{ "=RedirectingID"
     "=Feed" }--o{ "=RedirectingID"
     "=Feed" ||-right-o{ "=ExternalID"
     "=GTFSRealtimeFeed" --o{ "=EntityTypeFeed"
     "=EntityType" -left-|{ "=EntityTypeFeed"
     "=GTFSRealtimeFeed" }|-right-o{ "=FeedReference"
     "=GTFSFeed" }o--o{ "=FeedReference"
     "=GTFSFeed" --|{ "=LocationFeed"
     "=Location" --|{ "=LocationFeed"
     "=Location" --|{ "=LocationGTFSDataset"
     "=GTFSDataset" -left-|{ "=LocationGTFSDataset"
     "=GTFSFeed" ||-left-o{ "=GTFSDataset"
     "=ComponentGTFSDataset" }o-left- "=GTFSDataset"
     "=ComponentGTFSDataset" }|-- "=Component"
@enduml