services:
  postgres:
    container_name: local_db
    image: postgis/postgis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MobilityDatabase
      - POSTGRES_PORT=5432
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - local
  liquibase:
    container_name: liquibase_update
    image: liquibase/liquibase
    volumes:
      - ../liquibase:/liquibase/changelog
    command:
      - --url=jdbc:postgresql://postgres:5432/MobilityDatabase
      - --changeLogFile=changelog.xml
      - --username=postgres
      - --password=postgres
      - --log-level=1
      - update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local
networks:
  local:
    driver: bridge