# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class FeedUrls(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FeedUrls - a model defined in OpenAPI

        producer_url: The producer_url of this FeedUrls [Optional].
        authentication_type: The authentication_type of this FeedUrls [Optional].
        authentication_info_url: The authentication_info_url of this FeedUrls [Optional].
        api_key_parameter_name: The api_key_parameter_name of this FeedUrls [Optional].
        latest_dataset_id: The latest_dataset_id of this FeedUrls [Optional].
        latest_hosted_url: The latest_hosted_url of this FeedUrls [Optional].
        license_url: The license_url of this FeedUrls [Optional].
    """

    producer_url: Optional[str] = Field(alias="producer_url", default=None)
    authentication_type: Optional[int] = Field(alias="authentication_type", default=None)
    authentication_info_url: Optional[str] = Field(alias="authentication_info_url", default=None)
    api_key_parameter_name: Optional[str] = Field(alias="api_key_parameter_name", default=None)
    latest_dataset_id: Optional[str] = Field(alias="latest_dataset_id", default=None)
    latest_hosted_url: Optional[str] = Field(alias="latest_hosted_url", default=None)
    license_url: Optional[str] = Field(alias="license_url", default=None)

FeedUrls.update_forward_refs()
