# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from feeds.models.feed_location import FeedLocation
from feeds.models.feed_urls import FeedUrls


class GtfsFeedAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GtfsFeedAllOf - a model defined in OpenAPI

        location: The location of this GtfsFeedAllOf [Optional].
        urls: The urls of this GtfsFeedAllOf [Optional].
    """

    location: Optional[FeedLocation] = Field(alias="location", default=None)
    urls: Optional[FeedUrls] = Field(alias="urls", default=None)

GtfsFeedAllOf.update_forward_refs()
