#
#   MobilityData 2025
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import logging
import os
import requests
from datetime import datetime, timedelta
from typing import List, Final, Optional

from google.cloud import storage
from sqlalchemy import or_
from sqlalchemy.orm import Session

from shared.database.database import with_db_session
from shared.database_gen.sqlacodegen_models import (
    Feed,
    Gtfsfeed,
    Gtfsdataset,
    Validationreport,
)
from shared.helpers.gtfs_validator_common import (
    get_gtfs_validator_results_bucket,
    get_gtfs_validator_url,
)
from shared.helpers.task_execution.task_execution_tracker import TaskExecutionTracker
from shared.helpers.validation_report.validation_report_update import execute_workflows

QUERY_LIMIT: Final[int] = 100
TASK_NAME: Final[str] = "gtfs_validation"

env = os.getenv("ENVIRONMENT", "dev").lower()
datasets_bucket_name = f"mobilitydata-datasets-{env}"


def rebuild_missing_validation_reports_handler(payload) -> dict:
    """
    Rebuilds missing validation reports for GTFS datasets.

    Handles two cases:
      1. Datasets with no validation report at all (ongoing maintenance).
      2. Datasets whose existing report was generated by an older validator version
         (triggered by passing validator_endpoint, used during validator releases).

    Payload structure:
    {
        "dry_run": bool,             # [optional] If True, count only — do not trigger workflows. Default: True
        "filter_after_in_days": int, # [optional] Restrict to datasets downloaded within the last N days.
                                     #   If omitted, all datasets are considered regardless of age.
        "filter_statuses": list[str],# [optional] Filter feeds by status
        "filter_op_statuses": list[str],# [optional] Filter feeds by operational status.
                                     #   Default: ["published"]
                                     #   Accepted values: "published", "unpublished", "wip"
        "validator_endpoint": str,   # [optional] Override validator URL (e.g. staging). Default: env-derived URL.
        "bypass_db_update": bool,    # [optional] If True, results are NOT written to the DB/API (pre-release runs).
            Default: False
        "force_update": bool,        # [optional] Re-trigger even if a report already exists. Default: False
        "limit": int,                # [optional] Max datasets to trigger per call (for testing). Default: unlimited
        "reports_bucket_name": str,  # [optional] Override the GCS bucket for validator results.
                                     #   Defaults to the env-derived bucket (prod or staging).
                                     #   Use when running in prod but pointing to the staging validator.
    }
    """
    (
        dry_run,
        filter_after_in_days,
        filter_statuses,
        filter_op_statuses,
        prod_env,
        validator_endpoint,
        bypass_db_update,
        force_update,
        limit,
        reports_bucket_name,
    ) = get_parameters(payload)

    return rebuild_missing_validation_reports(
        validator_endpoint=validator_endpoint,
        bypass_db_update=bypass_db_update,
        dry_run=dry_run,
        filter_after_in_days=filter_after_in_days,
        filter_statuses=filter_statuses,
        filter_op_statuses=filter_op_statuses,
        prod_env=prod_env,
        force_update=force_update,
        limit=limit,
        reports_bucket_name=reports_bucket_name,
    )


@with_db_session
def rebuild_missing_validation_reports(
    validator_endpoint: str,
    bypass_db_update: bool = False,
    dry_run: bool = True,
    filter_after_in_days: Optional[int] = None,
    filter_statuses: List[str] | None = None,
    filter_op_statuses: List[str] | None = None,
    prod_env: bool = False,
    force_update: bool = False,
    limit: Optional[int] = None,
    reports_bucket_name: Optional[str] = None,
    db_session: Session | None = None,
) -> dict:
    """
    Rebuilds missing (or stale) validation reports for GTFS datasets.

    Args:
        validator_endpoint: Validator service URL (default: env-derived)
        bypass_db_update: If True, validation results are NOT written to the DB/API.
            Use for pre-release runs where results should not be surfaced yet.
        dry_run: If True, count only — do not trigger workflows. Default: True
        filter_after_in_days: Restrict to datasets downloaded within the last N days.
            If None (default), all datasets are considered regardless of age.
        filter_statuses: Filter feeds by status. Default: None (all)
        filter_op_statuses: Filter feeds by operational status.
            Default: ["published"]. Accepted: "published", "unpublished", "wip".
        prod_env: True if targeting the production environment. Default: False
        force_update: Re-trigger even if a report already exists. Default: False
        limit: Max datasets to trigger per call (for end-to-end testing). Default: unlimited
        reports_bucket_name: Override the GCS bucket for validator results.
            Defaults to the env-derived bucket (prod or staging).
        db_session: DB session (injected by @with_db_session)
    """
    validator_version = _get_validator_version(validator_endpoint)
    logging.info(
        "Validator version: %s (bypass_db_update=%s)",
        validator_version,
        bypass_db_update,
    )

    datasets = _get_datasets_for_validation(
        db_session=db_session,
        validator_version=validator_version,
        force_update=force_update,
        filter_after_in_days=filter_after_in_days,
        filter_statuses=filter_statuses,
        filter_op_statuses=filter_op_statuses
        if filter_op_statuses is not None
        else ["published"],
    )
    total_candidates = len(datasets)
    logging.info("Found %s candidate datasets", total_candidates)

    # Apply limit inside the GCS blob check so we stop as soon as we have
    # enough valid datasets, without discarding candidates that would pass.
    valid_datasets = _filter_out_datasets_without_blob(datasets, limit=limit)
    logging.info(
        "%s datasets have a GCS blob and will be triggered", len(valid_datasets)
    )

    tracker = TaskExecutionTracker(
        task_name=TASK_NAME,
        run_id=validator_version,
        db_session=db_session,
    )

    datasets_to_trigger = valid_datasets

    if not dry_run:
        tracker.start_run(
            total_count=len(datasets_to_trigger),
            params={
                "validator_endpoint": validator_endpoint,
                "bypass_db_update": bypass_db_update,
                "prod_env": prod_env,
                "force_update": force_update,
                "limit": limit,
                "total_candidates": total_candidates,
            },
        )
        tracker.schedule_status_sync(delay_seconds=600)

    total_triggered = 0
    total_skipped = 0
    total_already_tracked = 0

    if dry_run:
        entity_ids = [d[1] for d in datasets_to_trigger]
        total_already_tracked = tracker.count_already_tracked(entity_ids)
        logging.info(
            "Dry run: %s datasets would be triggered (%s already tracked, would be skipped)",
            len(datasets_to_trigger),
            total_already_tracked,
        )
    else:
        triggered_ids = execute_workflows(
            datasets_to_trigger,
            validator_endpoint=validator_endpoint,
            bypass_db_update=bypass_db_update,
            reports_bucket_name=reports_bucket_name
            or get_gtfs_validator_results_bucket(prod_env),
            tracker=tracker,
        )
        total_triggered = len(triggered_ids)
        total_skipped = len(datasets_to_trigger) - total_triggered
        db_session.commit()

    message = (
        f"Dry run: {len(datasets_to_trigger)} datasets would be triggered "
        f"({total_already_tracked} already tracked, would be skipped)."
        if dry_run
        else f"Triggered {total_triggered} workflows ({total_skipped} skipped — already tracked)."
    )
    result = {
        "message": message,
        "total_candidates": total_candidates,
        "total_in_call": len(datasets_to_trigger),
        "total_triggered": 0 if dry_run else total_triggered,
        "total_skipped": 0 if dry_run else total_skipped,
        "total_already_tracked": total_already_tracked,
        "params": {
            "dry_run": dry_run,
            "validator_version": validator_version,
            "validator_endpoint": validator_endpoint,
            "bypass_db_update": bypass_db_update,
            "filter_after_in_days": filter_after_in_days,
            "filter_statuses": filter_statuses,
            "prod_env": prod_env,
            "force_update": force_update,
            "limit": limit,
            "reports_bucket_name": reports_bucket_name
            or get_gtfs_validator_results_bucket(prod_env),
        },
    }
    logging.info(result)
    return result


def _get_validator_version(validator_endpoint: str) -> str:
    """Fetch the current version string from the validator service."""
    response = requests.get(f"{validator_endpoint}/version", timeout=30)
    response.raise_for_status()
    version = response.json()["version"]
    logging.info("Validator version: %s", version)
    return version


def _get_datasets_for_validation(
    db_session: Session,
    validator_version: str,
    force_update: bool,
    filter_after_in_days: Optional[int],
    filter_statuses: Optional[List[str]],
    filter_op_statuses: Optional[List[str]],
) -> List[tuple]:
    """
    Query datasets that need a (re)validation.

    Includes datasets that:
      - Have no validation report at all, OR
      - Have a report from a different (older) validator version, OR
      - force_update is True

    filter_after_in_days restricts to datasets downloaded within the last N days.
    When None, all datasets are included regardless of age.
    filter_op_statuses filters by Feed.operational_status (e.g. ["published"]).
    """
    query = (
        db_session.query(Gtfsfeed.stable_id, Gtfsdataset.stable_id)
        .select_from(Gtfsfeed)
        .join(Gtfsdataset, Gtfsfeed.latest_dataset_id == Gtfsdataset.id)
        .outerjoin(Validationreport, Gtfsdataset.validation_reports)
        .filter(
            or_(
                Validationreport.id.is_(None),
                Validationreport.validator_version != validator_version,
                force_update,
            )
        )
        .distinct(Gtfsfeed.stable_id, Gtfsdataset.stable_id)
        .order_by(Gtfsdataset.stable_id, Gtfsfeed.stable_id)
    )
    if filter_after_in_days is not None:
        filter_after = datetime.today() - timedelta(days=filter_after_in_days)
        query = query.filter(Gtfsdataset.downloaded_at >= filter_after)
    if filter_statuses:
        query = query.filter(Gtfsfeed.status.in_(filter_statuses))
    if filter_op_statuses:
        query = query.filter(Feed.operational_status.in_(filter_op_statuses))

    return query.all()


def _filter_out_datasets_without_blob(
    datasets: List[tuple],
    limit: Optional[int] = None,
) -> List[tuple]:
    """
    Filter out datasets whose zip file does not exist in GCS.
    This avoids triggering workflows for feeds that have no data to validate.

    When limit is provided, stops as soon as limit valid datasets are found,
    avoiding unnecessary GCS calls for the remaining candidates.
    """
    storage_client = storage.Client()
    bucket = storage_client.bucket(datasets_bucket_name)
    valid = []
    for feed_id, dataset_id in datasets:
        if limit is not None and len(valid) >= limit:
            break
        try:
            blob = bucket.blob(f"{feed_id}/{dataset_id}/{dataset_id}.zip")
            if blob.exists():
                valid.append((feed_id, dataset_id))
            else:
                logging.warning(
                    "No GCS blob found for %s/%s — skipping", feed_id, dataset_id
                )
        except Exception as e:
            logging.error(
                "Error checking GCS blob for %s/%s: %s", feed_id, dataset_id, e
            )
    return valid


def get_parameters(payload):
    """
    Extract and coerce parameters from the task payload.

    Args:
        payload (dict): Task payload dict.
    Returns:
        Tuple of (dry_run, filter_after_in_days, filter_statuses, filter_op_statuses,
                  prod_env, validator_endpoint, bypass_db_update, force_update, limit,
                  reports_bucket_name)
    """
    prod_env = os.getenv("ENVIRONMENT", "").lower() == "prod"
    default_endpoint = get_gtfs_validator_url(prod_env)

    dry_run = payload.get("dry_run", True)
    dry_run = dry_run if isinstance(dry_run, bool) else str(dry_run).lower() == "true"

    filter_after_in_days = payload.get("filter_after_in_days", None)
    if filter_after_in_days is not None:
        filter_after_in_days = (
            filter_after_in_days
            if isinstance(filter_after_in_days, int)
            else int(filter_after_in_days)
        )

    filter_statuses = payload.get("filter_statuses", None)

    filter_op_statuses = payload.get("filter_op_statuses", None)

    validator_endpoint = payload.get("validator_endpoint", default_endpoint)

    bypass_db_update = payload.get("bypass_db_update", False)
    bypass_db_update = (
        bypass_db_update
        if isinstance(bypass_db_update, bool)
        else str(bypass_db_update).lower() == "true"
    )

    force_update = payload.get("force_update", False)
    force_update = (
        force_update
        if isinstance(force_update, bool)
        else str(force_update).lower() == "true"
    )

    limit = payload.get("limit", None)
    if limit is not None:
        limit = int(limit)

    reports_bucket_name = payload.get("reports_bucket_name", None)

    return (
        dry_run,
        filter_after_in_days,
        filter_statuses,
        filter_op_statuses,
        prod_env,
        validator_endpoint,
        bypass_db_update,
        force_update,
        limit,
        reports_bucket_name,
    )
