openapi: 3.0.0
info:
  version: 0.1.0
  title: Mobility Data Catalog API
  description: API to interact with tokens from the Mobility Database API
  termsOfService: https://mobilitydata.org/terms-of-use
  contact:
    name: MobilityData
    url: https://mobilitydata.org/
    email: api@mobilitydata.org
  license:
    name: MobilityData License
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: https://api.mobilitydatabase.org/
    description: Prod release environment
  - url: https://api-qa.mobilitydatabase.org/
    description: Pre-prod environment
  - url: https://api-dev.mobilitydatabase.org/
    description: Development environment
  - url: http://localhost:8080/
    description: Local development environment

tags:
  - name: "tokens"
    description: "Token to access the Mobility Database API"

paths:
  /v1/tokens/access:
    post:
      description: Create an access token.
      tags:
        - "tokens"
      operationId: postAccessToken
      requestBody:
        description: Generates an access token from a refresh token
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostAccessTokenBody"
        required: true
      responses:
        200:
          description: Successful generated the access token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostAccessTokenResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    PostAccessTokenBody:
      type: object
      properties:
        refresh_token:
          type: string
      required:
        - refresh_token
    PostAccessTokenResponse:
      type: object
      properties:
        access_token:
          type: string
        expiration_datetime_utc:
          type: string
          format: date-time
          example: "2020-01-01T00:00:00Z"
        token_type:
          type: string
          example: "Bearer"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
