openapi: 3.0.0
info:
  version: 1.0.0
  title: Mobility Database Catalog Operations
  description: |
    API for the Mobility Database Catalog Operations. See [https://mobilitydatabase.org/](https://mobilitydatabase.org/).
    This API was designed for internal use and is not intended to be used by the general public.
    The Mobility Database Operation API uses Auth2.0 authentication.
  termsOfService: https://mobilitydatabase.org/terms-and-conditions
  contact:
    name: MobilityData
    url: https://mobilitydata.org/
    email: api@mobilitydata.org
  license:
    name: MobilityData License
    url: https://www.apache.org/licenses/LICENSE-2.0

tags:
  - name: "operations"
    description: "Mobility Database Operations"

paths:
  /v1/operations/feeds:
    get:
      description: Get a list of feeds with optional filtering and pagination.
      operationId: getFeeds
      tags:
        - "operations"
      parameters:
        - name: operation_status
          in: query
          description: Filter feeds by operational status.
          required: false
          schema:
            type: string
            enum: [ wip, published, unpublished ]
        - name: data_type
          in: query
          description: Filter feeds by data type.
          required: false
          schema:
            type: string
            enum: [ gtfs, gtfs_rt ]
        - name: offset
          in: query
          description: Number of items to skip for pagination.
          required: false
          schema:
            type: string
            default: "0"
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          schema:
            type: string
            default: "50"
            example: "100"
      responses:
        200:
          description: List of feeds retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  feeds:
                    type: array
                    items:
                      $ref: "#/components/schemas/BaseFeed"
        401:
          description: Unauthorized.
        500:
          description: Internal Server Error.

  /v1/operations/feeds/gtfs:
    put:
      description: Update the specified GTFS feed in the Mobility Database.
      tags:
        - "operations"
      operationId: updateGtfsFeed
      security:
        - ApiKeyAuth: [ ]
      requestBody:
        description: Payload to update the specified GTFS feed.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRequestGtfsFeed"
      responses:
        200:
          description: >
            The feed was successfully updated. No content is returned.
        204:
          description: >
            The feed update request was successfully received, but the update process was skipped as the request matches with the source feed.
        400:
          description: >
            The request was invalid.
        401:
          description: >
            The request was not authenticated or has invalid authentication credentials.
        500:
          description: >
            An internal server error occurred.

  /v1/operations/feeds/gtfs_rt:
    put:
      description: Update the specified GTFS-RT feed in the Mobility Database.
      tags:
        - "operations"
      operationId: updateGtfsRtFeed
      security:
        - ApiKeyAuth: [ ]
      requestBody:
        description: Payload to update the specified GTFS-RT feed.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRequestGtfsRtFeed"
      responses:
        200:
          description: >
            The feed was successfully updated. No content is returned.
        204:
          description: >
            The feed update request was successfully received, but the update process was skipped as the request matches with the source feed.
        400:
          description: >
            The request was invalid.
        401:
          description: >
            The request was not authenticated or has invalid authentication credentials.
        500:
          description: >
            An internal server error occurred.

components:
  schemas:
    BaseFeed:
      type: object
      discriminator:
        propertyName: data_type
        mapping:
          gtfs: '#/components/schemas/GtfsFeedResponse'
          gtfs_rt: '#/components/schemas/GtfsRtFeedResponse'
      properties:
        id:
          type: string
          description: Unique identifier for the feed.
        stable_id:
          type: string
          description: Stable identifier for the feed.
        status:
          $ref: "#/components/schemas/FeedStatus"
        data_type:
          $ref: "#/components/schemas/DataType"
        provider:
          type: string
          description: Name of the transit provider.
        feed_name:
          type: string
          description: Name of the feed.
        note:
          type: string
          description: Additional notes about the feed.
        feed_contact_email:
          type: string
          description: Contact email for the feed.
        source_info:
          $ref: "#/components/schemas/SourceInfo"
        operational_status:
          type: string
          enum: [ wip, published, unpublished ]
          description: Current operational status of the feed.
        created_at:
          type: string
          format: date-time
          description: When the feed was created.
        official:
          type: boolean
          description: Whether this is an official feed.
        official_updated_at:
          type: string
          format: date-time
          description: When the official status was last updated.
        locations:
          type: array
          items:
            $ref: "#/components/schemas/Location"
        external_ids:
          type: array
          items:
            $ref: "#/components/schemas/ExternalId"
        redirects:
          type: array
          items:
            $ref: "#/components/schemas/Redirect"

    GtfsFeedResponse:
      allOf:
        - $ref: "#/components/schemas/BaseFeed"
        - type: object
          description: GTFS feed response model.

    GtfsRtFeedResponse:
      allOf:
        - $ref: "#/components/schemas/BaseFeed"
        - type: object
          properties:
            entity_types:
              type: array
              items:
                type: string
                enum:
                  - vp
                  - tu
                  - sa
                example: vp
                description: >
                  The type of realtime entry:
                    * vp - vehicle positions
                    * tu - trip updates
                    * sa - service alerts
            feed_references:
              description:
                A list of the GTFS feeds that the real time source is associated with, represented by their MDB source IDs.
              type: array
              items:
                type: string
                example: "mdb-20"

    GetFeeds200Response:
      type: object
      properties:
        total:
          type: integer
          description: Total number of feeds matching the criteria.
        offset:
          type: string
          description: Current offset for pagination.
        limit:
          type: string
          description: Maximum number of items per page.
        feeds:
          type: array
          items:
            $ref: "#/components/schemas/BaseFeed"
          description: List of feeds.

    Redirect:
      type: object
      properties:
        target_id:
          description: The feed ID that should be used in replacement of the current one.
          type: string
          example: mdb-10
        comment:
          description: A comment explaining the redirect.
          type: string
          example: Redirected because of a change of URL.

    UpdateRequestGtfsRtFeed:
      type: object
      properties:
        id:
          description: Unique identifier used as a key for the feeds table.
          type: string
          example: mdb-1210
        status:
          $ref: "#/components/schemas/FeedStatus"
        external_ids:
          $ref: "#/components/schemas/ExternalIds"
        provider:
          description: A commonly used name for the transit provider included in the feed.
          type: string
          example: Los Angeles Department of Transportation (LADOT, DASH, Commuter Express)
        feed_name:
          description: >
            An optional description of the data feed, e.g to specify if the data feed is an aggregate of
            multiple providers, or which network is represented by the feed.
          type: string
          example: Bus
        note:
          description: A note to clarify complex use cases for consumers.
          type: string
        feed_contact_email:
          description: Use to contact the feed producer.
          type: string
          example: someEmail@ladotbus.com
        source_info:
          $ref: "#/components/schemas/SourceInfo"
        redirects:
          type: array
          items:
            $ref: "#/components/schemas/Redirect"
        entity_types:
          type: array
          items:
            $ref: "#/components/schemas/EntityType"
        feed_references:
          description:
            A list of the GTFS feeds that the real time source is associated with, represented by their MDB source IDs.
          type: array
          items:
            type: string
            example: "mdb-20"
        operational_status_action:
          type: string
          enum:
            - no_change
            - wip
            - published
            - unpublished
        official:
          type: boolean
          description: Whether this is an official feed.
      required:
        - id
        - status
        - entity_types

    UpdateRequestGtfsFeed:
      type: object
      properties:
        id:
          description: Unique identifier used as a key for the feeds table.
          type: string
          example: mdb-1210
        status:
          $ref: "#/components/schemas/FeedStatus"
        external_ids:
          $ref: "#/components/schemas/ExternalIds"
        provider:
          description: A commonly used name for the transit provider included in the feed.
          type: string
          example: Los Angeles Department of Transportation (LADOT, DASH, Commuter Express)
        feed_name:
          description: >
            An optional description of the data feed, e.g to specify if the data feed is an aggregate of
            multiple providers, or which network is represented by the feed.
          type: string
          example: Bus
        note:
          description: A note to clarify complex use cases for consumers.
          type: string
        feed_contact_email:
          description: Use to contact the feed producer.
          type: string
          example: someEmail@ladotbus.com
        source_info:
          $ref: "#/components/schemas/SourceInfo"
        redirects:
          type: array
          items:
            $ref: "#/components/schemas/Redirect"
        operational_status_action:
          type: string
          enum:
            - no_change
            - wip
            - published
            - unpublished
        official:
          type: boolean
          description: Whether this is an official feed.
      required:
        - id
        - status

    ExternalIds:
      type: array
      items:
        $ref: "#/components/schemas/ExternalId"

    ExternalId:
      type: object
      properties:
        external_id:
          description: The ID that can be use to find the feed data in an external or legacy database.
          type: string
          example: 1210
        source:
          description: The source of the external ID, e.g. the name of the database where the external ID can be used.
          type: string
          example: mdb

    SourceInfo:
      type: object
      properties:
        producer_url:
          description: >
            URL where the producer is providing the dataset.
            Refer to the authentication information to know how to access this URL.
          type: string
          format: url
          example: https://ladotbus.com/gtfs
        authentication_type:
          $ref: "#/components/schemas/Authentication_type"
        authentication_info_url:
          description: >
            Contains a URL to a human-readable page describing how the authentication should be performed and how credentials can be created.
            This field is required for `authentication_type=1` and `authentication_type=2`.
          type: string
          format: url
          example: https://apidevelopers.ladottransit.com
        api_key_parameter_name:
          type: string
          description: >
            Defines the name of the parameter to pass in the URL to provide the API key.
            This field is required for `authentication_type=1` and `authentication_type=2`.
          example: Ocp-Apim-Subscription-Key
        license_url:
          description: A URL where to find the license for the feed.
          type: string
          format: url
          example: https://www.ladottransit.com/dla.html

    EntityType:
      type: string
      enum:
        - vp
        - tu
        - sa
      example: vp
      description: >
        The type of realtime entry:
          * vp - vehicle positions
          * tu - trip updates
          * sa - service alerts

    FeedStatus:
      description: >
        Describes status of the Feed. Should be one of
          * `active` Feed should be used in public trip planners.
          * `deprecated` Feed is explicitly deprecated and should not be used in public trip planners.
          * `inactive` Feed hasn't been recently updated and should be used at risk of providing outdated information.
          * `development` Feed is being used for development purposes and should not be used in public trip planners.
          * `future` Feed is not yet active but will be in the future.
      type: string
      enum:
        - active
        - deprecated
        - inactive
        - development
        - future
      example: active

    DataType:
      description: >
        Describes data type of a feed. Should be one of
          * `gtfs` GTFS feed.
          * `gtfs_rt` GTFS-RT feed.
          * `gbfs` GBFS feed.
      type: string
      enum:
        - gtfs
        - gtfs_rt
        - gbfs
      example: gtfs

    Authentication_type:
      description: >
        Defines the type of authentication required to access the `producer_url`. Valid values for this field are:
          * 0 or (empty) - No authentication required.
          * 1 - The authentication requires an API key, which should be passed as value of the parameter api_key_parameter_name in the URL. Please visit URL in authentication_info_url for more information.
          * 2 - The authentication requires an HTTP header, which should be passed as the value of the header api_key_parameter_name in the HTTP request.
        When not provided, the authentication type is assumed to be 0.
      type: integer
      enum:
        - 0
        - 1
        - 2
      example: 2

    Location:
      type: object
      properties:
        country_code:
          type: string
          description: ISO 3166-1 alpha-2 country code.
        country:
          type: string
          description: English name of the country.
        subdivision_name:
          type: string
          description: Name of the subdivision (state/province/region).
        municipality:
          type: string
          description: Name of the municipality.

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: x-api-key
      in: header

security:
  - ApiKeyAuth: [ ]
