ALTER TABLE gtfsdataset 
ALTER COLUMN service_date_range_start 
SET DATA TYPE TIMESTAMP WITH TIME ZONE 
USING service_date_range_start::TIMESTAMP WITH TIME ZONE,

ALTER COLUMN service_date_range_end 
SET DATA TYPE TIMESTAMP WITH TIME ZONE 
USING service_date_range_end::TIMESTAMP WITH TIME ZONE;