CREATE TABLE IF NOT EXISTS GeopolygonHierarchy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    osm_id INTEGER NOT NULL UNIQUE REFERENCES Geopolygon(osm_id) ON DELETE CASCADE,
    parent_osm_id INTEGER REFERENCES Geopolygon(osm_id) ON DELETE SET NULL,
    country_osm_id INTEGER REFERENCES Geopolygon(osm_id) ON DELETE SET NULL,
    subdivision_osm_id INTEGER REFERENCES Geopolygon(osm_id) ON DELETE SET NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (osm_id <> parent_osm_id),
    CHECK (osm_id <> country_osm_id),
    CHECK (osm_id <> subdivision_osm_id)
);

CREATE INDEX IF NOT EXISTS idx_geopolygonhierarchy_parent_osm_id ON GeopolygonHierarchy(parent_osm_id);
CREATE INDEX IF NOT EXISTS idx_geopolygonhierarchy_country_osm_id ON GeopolygonHierarchy(country_osm_id);
CREATE INDEX IF NOT EXISTS idx_geopolygonhierarchy_subdivision_osm_id ON GeopolygonHierarchy(subdivision_osm_id);
