name: API Version
on:
  workflow_call:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Write commit hash to JSON file
        run: |
          echo "{ \"commit_hash\": \"$COMMIT_HASH\" }" > ./github/version.json

      - name: Update version during release
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            jq '.version = env.VERSION' ./github/version.json > temp.json && mv temp.json ./github/version.json
          fi
        env:
          VERSION: ${{ github.ref }}
