name: Build and Test
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_call:

env:
  python_version: '3.10'
  java_version: '11' # needed by setup-openapi-generator.sh

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Build & Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Docker Compose DB
        run: |
          docker-compose --env-file ./config/.env.local up -d postgres postgres-test
        working-directory: ${{ github.workspace }}

      - name: Run lint checks
        shell: bash
        run: |
          scripts/lint-tests.sh

      - name: Install Liquibase
        run: |    
          wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg && \
          cat liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null && \
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list
      
          sudo apt-get update
          sudo apt-get install liquibase

#      Uncomment the following block to test the databases
#      - name: Test Database Connection
#        run: |
#          sudo apt-get update && sudo apt-get install -y postgresql-client
#          PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d MobilityDatabase -c "SELECT version();"
#          PGPASSWORD=postgres psql -h localhost -p 54320 -U postgres -d MobilityDatabaseTest -c "SELECT version();"

      - name: Run Liquibase on Python functions test DB
        run: |
          export LIQUIBASE_CLASSPATH="liquibase"
          export LIQUIBASE_COMMAND_CHANGELOG_FILE="changelog.xml"
          export LIQUIBASE_COMMAND_URL=jdbc:postgresql://localhost:54320/MobilityDatabaseTest
          export LIQUIBASE_COMMAND_USERNAME=postgres
          export LIQUIBASE_COMMAND_PASSWORD=postgres
          liquibase update

      - name: Run Liquibase on API test DB
        run: |      
          export LIQUIBASE_CLASSPATH="liquibase"
          export LIQUIBASE_COMMAND_CHANGELOG_FILE="changelog.xml"
          export LIQUIBASE_COMMAND_URL=jdbc:postgresql://localhost:5432/MobilityDatabase
          export LIQUIBASE_COMMAND_USERNAME=postgres
          export LIQUIBASE_COMMAND_PASSWORD=postgres
          export LIQUIBASE_LOG_LEVEL=FINE
      
          liquibase update

#      - name: Install Liquibase
#        run: |
#          wget -O- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg && \
#          cat liquibase-keyring.gpg | sudo tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null && \
#          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | sudo tee /etc/apt/sources.list.d/liquibase.list
#
#          sudo apt-get update
#          sudo apt-get install liquibase

      - name: Generate DB code
        run: |
          scripts/db-gen.sh

      - name: Generate API code
        run: |
          scripts/setup-openapi-generator.sh
          scripts/api-gen.sh

      - name: Unit tests - API
        shell: bash
        run: |
          scripts/api-tests.sh --folder api --html_report

      - name: Unit tests - Python Functions
        shell: bash
        run: |
          scripts/api-tests.sh --folder functions-python --html_report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: scripts/coverage_reports/
