name: Deploy Historical Batch Processing - DEV

on:
  workflow_dispatch:  # Supports manual deployment
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/datasets-batch-deployer.yml
    with:
      FUNCTION_BUCKET_NAME: 'mobility-batch-processing'
      STATE_BUCKET_NAME: 'mobility-feeds-terraform-dev'
      OBJECT_PREFIX: 'terraform-state-datasets-batch'
      PROJECT_ID: 'mobility-feeds-dev'
      REGION: 'us-central1'
      DEPLOYER_SERVICE_ACCOUNT: 'ci-impersonator@mobility-feeds-dev.iam.gserviceaccount.com'
      SOURCE_ZIP_PATH: 'datasets/'
      SOURCE_CODE_ZIP_FILE: 'datasets.zip'
      HTTP_FUNCTION_NAME: 'batch-datasets'
      PUBSUB_FUNCTION_NAME: 'process-dataset'
      RUNTIME: 'python310'
      HTTP_ENTRY_POINT: 'batch_datasets'
      PUBSUB_ENTRY_POINT: 'process_dataset'
      AVAILABLE_MEMORY: '2Gi'
      AVAILABLE_CPU: '1'
      PUBSUB_TIMEOUT_SECONDS: '540'
      HTTP_TIMEOUT_SECONDS: '3600'
      MAX_INSTANCE_COUNT: '50'
      JOB_NAME: 'dataset-batch-job'
      JOB_DESCRIPTION: 'Run python function daily'
      JOB_SCHEDULE: '0 0 * * *'
      JOB_HTTP_METHOD: 'GET'
      JOB_ATTEMPT_DEADLINE: '320s'
      PUBSUB_TOPIC_NAME: 'datasets-batch-topic'
      CREATE_PUBSUB_FUNCTION: true
      DATASETS_BUCKET: 'mobility-datasets'
      POSTGRES_DB: ${{ vars.DEV_POSTGRE_SQL_DB_NAME }}
      POSTGRES_PORT: 5432
    secrets:
      POSTGRES_USER: ${{ secrets.DEV_POSTGRE_USER_NAME }}
      POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRE_USER_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DEV_DB_PUBLIC_IP }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.DEV_GCP_MOBILITY_FEEDS_SA_KEY }}
