name: Deploy Historical Batch Processing - DEV

on:
  workflow_dispatch:  # Supports manual deployment
  push:
    branches:
      - main
      - 'feat/173'

jobs:
  deploy:
    uses: ./.github/workflows/datasets-batch-deployer.yml
    with:
      STATE_BUCKET_NAME: 'mobility-feeds-terraform-dev'
      OBJECT_PREFIX: 'terraform-state-batch'
      PROJECT_ID: ${{ vars.DEV_MOBILITY_FEEDS_PROJECT_ID }}
      REGION: 'northamerica-northeast1'
      ENVIRONMENT: 'dev'
      DEPLOYER_SERVICE_ACCOUNT: ${{ vars.DEV_MOBILITY_FEEDS_DEPLOYER_SERVICE_ACCOUNT }}
      # every week on monday at 00:00
      JOB_SCHEDULE: '0 0 * * 1'
      DATASETS_BUCKET_NAME: 'mobilitydata-datasets-dev'
    secrets:
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.DEV_GCP_MOBILITY_FEEDS_SA_KEY }}
