# Deploys the Mobility Database to the DEV environment
name: Deploy DB - PROD
on:
  workflow_dispatch: # Supports manual deployment

jobs:
  deploy:
    uses: ./.github/workflows/db-deployer.yml
    with:
      ENVIRONMENT: ${{ vars.PROD_MOBILITY_FEEDS_ENVIRONMENT }}
      BUCKET_NAME: ${{ vars.PROD_MOBILITY_FEEDS_TF_STATE_BUCKET }}
      OBJECT_PREFIX: ${{ vars.PROD_MOBILITY_DB_TF_STATE_OBJECT_PREFIX }}
      PROJECT_ID: ${{ vars.PROD_MOBILITY_FEEDS_PROJECT_ID }}
      REGION: ${{ vars.PROD_MOBILITY_FEEDS_REGION }}
      DEPLOYER_SERVICE_ACCOUNT: ${{ vars.PROD_MOBILITY_FEEDS_DEPLOYER_SERVICE_ACCOUNT }}
      POSTGRE_SQL_DB_NAME: ${{ vars.PROD_POSTGRE_SQL_DB_NAME }}
      POSTGRE_INSTANCE_TIER: ${{ vars.PROD_POSTGRE_INSTANCE_TIER }}
      TF_APPLY: true
    secrets:
      POSTGRE_USER_PASSWORD: ${{ secrets.PROD_POSTGRE_USER_PASSWORD }}
      POSTGRE_USER_NAME: ${{ secrets.PROD_POSTGRE_USER_NAME }}
      POSTGRE_SQL_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.PROD_GCP_MOBILITY_FEEDS_SA_KEY }}
