# Deploys the Mobility Database to the QA environment
name: Deploy DB - QA
on:
  workflow_dispatch:  # Supports manual deployment

jobs:
  deploy:
    uses: ./.github/workflows/db-deployer.yml
    with:
      ENVIRONMENT: ${{ vars.QA_MOBILITY_FEEDS_ENVIRONMENT }}
      BUCKET_NAME: ${{ vars.QA_MOBILITY_FEEDS_TF_STATE_BUCKET }}
      OBJECT_PREFIX: ${{ vars.QA_MOBILITY_DB_TF_STATE_OBJECT_PREFIX }}
      PROJECT_ID: ${{ vars.QA_MOBILITY_FEEDS_PROJECT_ID }}
      REGION: ${{ vars.MOBILITY_FEEDS_REGION }}
      DEPLOYER_SERVICE_ACCOUNT: ${{ vars.QA_MOBILITY_FEEDS_DEPLOYER_SERVICE_ACCOUNT }}
      POSTGRE_SQL_DB_NAME: ${{ vars.QA_POSTGRE_SQL_DB_NAME }}
      POSTGRE_INSTANCE_TIER: ${{ vars.QA_POSTGRE_INSTANCE_TIER }}
      MAX_CONNECTIONS: ${{ vars.DEV_DB_MAX_CONNECTIONS }}
      TF_APPLY: true
    secrets:
      POSTGRE_USER_PASSWORD: ${{ secrets.QA_POSTGRE_USER_PASSWORD }}
      POSTGRE_USER_NAME: ${{ secrets.QA_POSTGRE_USER_NAME }}
      POSTGRE_SQL_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.QA_GCP_MOBILITY_FEEDS_SA_KEY }}
      DEV_GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.DEV_GCP_MOBILITY_FEEDS_SA_KEY }}