# Update the Mobility Database Schema
name: Database Update - PROD
on:
  release: # Update on merge on master if the changelog file has been updated
    paths:
      - "liquibase/changelog.xml"
  workflow_dispatch:
  repository_dispatch: # Update on mobility-database-catalog repo dispatch
    types: [ catalog-sources-updated ]
jobs:
  update:
    uses: ./.github/workflows/db-update.yml
    with:
      PROJECT_ID: ${{ vars.PROD_MOBILITY_FEEDS_PROJECT_ID }}
      DB_NAME: ${{ vars.PROD_POSTGRE_SQL_DB_NAME }}
      REGION: ${{ vars.PROD_MOBILITY_FEEDS_REGION }}
    secrets:
      DB_USER_PASSWORD: ${{ secrets.PROD_POSTGRE_USER_PASSWORD }}
      DB_USER_NAME: ${{ secrets.PROD_POSTGRE_USER_NAME }}
      DB_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.PROD_GCP_MOBILITY_FEEDS_SA_KEY }}
