# Update the Mobility Database Schema
name: Database Update - PROD
on:
  workflow_dispatch:
    inputs:
      INSTALL_MODE:
        description: Which API version to install when run manually. "installed" = install the currently deployed API version; "latest" = install latest from main.
        required: false
        default: installed
        type: string
  workflow_call:
    inputs:
      INSTALL_MODE:
        description: Which API version to install when called as a reusable workflow (defaults to latest)
        required: false
        default: latest
        type: string
  repository_dispatch: # Update on mobility-database-catalog repo dispatch
    types: [ catalog-sources-updated, gbfs-systems-updated ]
jobs:
  update:
    uses: ./.github/workflows/db-update.yml
    with:
      PROJECT_ID: ${{ vars.PROD_MOBILITY_FEEDS_PROJECT_ID }}
      REGION: ${{ vars.MOBILITY_FEEDS_REGION }}
      DB_NAME: ${{ vars.PROD_POSTGRE_SQL_DB_NAME }}
      ENVIRONMENT: ${{ vars.PROD_MOBILITY_FEEDS_ENVIRONMENT }}
      DB_ENVIRONMENT: ${{ vars.PROD_MOBILITY_FEEDS_ENVIRONMENT }}
      API_BASE_URL: api.mobilitydatabase.org
      INSTALL_MODE: ${{ inputs.INSTALL_MODE }}
    secrets:
      DB_USER_PASSWORD: ${{ secrets.PROD_POSTGRE_USER_PASSWORD }}
      DB_USER_NAME: ${{ secrets.PROD_POSTGRE_USER_NAME }}
      DB_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.PROD_GCP_MOBILITY_FEEDS_SA_KEY }}
      DB_GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.PROD_GCP_MOBILITY_FEEDS_SA_KEY }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      OP_FEEDS_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_FEEDS_SERVICE_ACCOUNT_TOKEN }}
      POSTGRE_SQL_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      API_TEST_REFRESH_TOKEN: ${{ secrets.PROD_API_TEST_REFRESH_TOKEN }}

  notify-slack-on-failure:
    needs: [ update ]
    if: always() && (needs.update.result == 'failure') && (github.event_name == 'repository_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./.github/actions/notify-slack
        with:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PRIORITY: "high"
