# Update the Mobility Database Schema
name: PROD Database Update
on:
  release: # Update on merge on master if the changelog file has been updated
    paths:
      - "liquibase/changelog.xml"
  workflow_dispatch:
    inputs:
      RUN_POPULATE_SCRIPT:
        description: "Run populate script (true/false)"
        required: false
        default: false
jobs:
  update:
    uses: ./.github/workflows/db-update.yml
    with:
      PROJECT_ID: ${{ vars.PROD_MOBILITY_FEEDS_PROJECT_ID }}
      DB_NAME: ${{ vars.PROD_POSTGRE_SQL_DB_NAME }}
      REGION: ${{ vars.PROD_MOBILITY_FEEDS_REGION }}
      RUN_POPULATE_SCRIPT: ${{ github.event.inputs.RUN_POPULATE_SCRIPT || false }}
    secrets:
      DB_USER_PASSWORD: ${{ secrets.PROD_POSTGRE_USER_PASSWORD }}
      DB_USER_NAME: ${{ secrets.PROD_POSTGRE_USER_NAME }}
      DB_INSTANCE_NAME: ${{ secrets.DB_INSTANCE_NAME }}
      GCP_MOBILITY_FEEDS_SA_KEY: ${{ secrets.PROD_GCP_MOBILITY_FEEDS_SA_KEY }}
