name: Copy PROD DB to QA
on:
  workflow_dispatch:  # Supports manual deployment
  push:
    branches:
      - 1117-allow-qa-environment-to-use-prod-database-contents

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: gcloud_auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_MOBILITY_FEEDS_SA_KEY }}

      - name: GCloud Setup
        uses: google-github-actions/setup-gcloud@v2

      - name: Create DB dump bucket
        run: |
          DUMP_BUCKET_NAME="mobilitydata-database-dump-qa"
          BUCKET_PROJECT_ID=${{ QA_MOBILITY_FEEDS_PROJECT_ID }}
          GCP_REGION=${{ vars.MOBILITY_FEEDS_REGION }}
          BUCKET_PROJECT_ID="${{ vars.DEV_MOBILITY_FEEDS_PROJECT_ID }}"

          # Check if the bucket already exists
          if ! gsutil ls -b "gs://${BUCKET_NAME}" &> /dev/null; then
            echo "Bucket doesn't exist. Creating..."
            gsutil mb -l $GCP_REGION -p $BUCKET_PROJECT_ID "gs://${DUMP_BUCKET_NAME}"
          else
            echo "Bucket already exists."
          fi