name: Generate PlantUML
on:
  push:
    paths:
      - '**.pu'
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .
          message: "feat: automatic generate PlantUML image files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}