name: Production Release
on:
    workflow_dispatch:
    push: # Update on merge on main branch if the changelog file has been updated
        branches:
            - chore/production-release

jobs:
    bd-deployment:
        name: Database Deployment
        uses: ./.github/workflows/db-prod.yml
        secrets: inherit
    bd-update:
        name: Database Update
        uses: ./.github/workflows/db-update-prod.yml
        secrets: inherit
    bash-deployment:
        name: Bash Processes Deployment
        uses: ./.github/workflows/datasets-batch-deployer-prod.yml
        secrets: inherit
    api-deployment:
        name: API Deployment
        uses: ./.github/workflows/api-prod.yml
        secrets: inherit
    web-deployment:
        name: Web Deployment
        uses: ./.github/workflows/web-dev.yml
        secrets: inherit