name: Test JC
on:
  push:
    branches: [50-create-api-version-in-openapi2]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: # Supports manual deployment

jobs:
  extract_commit_hash:
    name: Extract Commit Hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Invoke extract-hash-and-version action
        uses: ./.github/actions/extract-hash-and-version

      - name: Display Commit Hash and version
        run: |
          echo "Commit Hash from file: `cat api/src/commit_hash`"
          echo "Version from file: `cat api/src/version`"
          echo "Commit Hash from var: $LONG_COMMIT_HASH"
          echo "Version from var: $VERSION"
          echo "Short commit hash: $SHORT_COMMIT_HASH"
          


