name: Test JC
on:
  push:
    branches: [testJC2]
  workflow_dispatch: # Supports manual deployment

jobs:
  extract_commit_hash:
    name: Extract Commit Hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Extract
        uses: ./.github/actions/checkout-and-extract
