name: Test JC
on:
  push:
    branches: [testJC2]
  workflow_dispatch: # Supports manual deployment

jobs:
  extract_commit_hash:
    name: Extract Commit Hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: test
        run: |
          pwd
          ls -l .
#      - name: Invoke checkout-and-extract.yaml
#        uses: ./.github/actions/checkout-and-extract
#        id: extract_hash
#
#      - name: Display Commit Hash and version
#        run: |
#          echo "Commit Hash: `cat api/src/commit_hash`"
#          echo "Version: `cat api/src/version`"


