name: TODO Delete this file
on:
  push:
jobs:
  test-key:
    runs-on: ubuntu-latest
    steps:
      - name: Load secret from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TRANSITLAND_API_KEY: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/TansitLand API Key/credential"
      - name: Print masked secret
        run: 'echo "Secret: TRANSITLAND_API_KEY=$TRANSITLAND_API_KEY"'
