name: Web App - DEV
on:
    workflow_dispatch:
    workflow_call:
    pull_request:
        branches: [main]
        paths:
            - "web-app/**"
            - "functions/**"
    push:
        branches:
          - main
          - chore/production-release            
jobs:
    deploy-web-app:
        name: Deploy Web App
        uses: ./.github/workflows/web-app-deployer.yml
        with:
          FIREBASE_PROJECT: dev
        secrets: inherit
