name: Web App - DEV
on:
    workflow_dispatch:
    workflow_call:

jobs:
    deploy-web-app:
        name: Deploy Web App
        uses: ./.github/workflows/web-app-deployer.yml
        with:
          FIREBASE_PROJECT: dev
        secrets: inherit
